// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/review.proto

package reviewpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReviewRequest) Reset() {
	*x = AddReviewRequest{}
	mi := &file_proto_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReviewRequest) ProtoMessage() {}

func (x *AddReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReviewRequest.ProtoReflect.Descriptor instead.
func (*AddReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{0}
}

func (x *AddReviewRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddReviewRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *AddReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsRequest) Reset() {
	*x = GetReviewsRequest{}
	mi := &file_proto_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsRequest) ProtoMessage() {}

func (x *GetReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{1}
}

func (x *GetReviewsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type EditReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      string                 `protobuf:"bytes,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditReviewRequest) Reset() {
	*x = EditReviewRequest{}
	mi := &file_proto_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditReviewRequest) ProtoMessage() {}

func (x *EditReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditReviewRequest.ProtoReflect.Descriptor instead.
func (*EditReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{2}
}

func (x *EditReviewRequest) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

func (x *EditReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *EditReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      string                 `protobuf:"bytes,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_proto_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteReviewRequest) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_proto_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{4}
}

func (x *GenericResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_proto_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{5}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Review) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsResponse) Reset() {
	*x = GetReviewsResponse{}
	mi := &file_proto_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsResponse) ProtoMessage() {}

func (x *GetReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetReviewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{6}
}

func (x *GetReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

var File_proto_review_proto protoreflect.FileDescriptor

const file_proto_review_proto_rawDesc = "" +
	"\n" +
	"\x12proto/review.proto\x12\x06review\"|\n" +
	"\x10AddReviewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"2\n" +
	"\x11GetReviewsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"b\n" +
	"\x11EditReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\tR\breviewId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"2\n" +
	"\x13DeleteReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\tR\breviewId\")\n" +
	"\x0fGenericResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x82\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\">\n" +
	"\x12GetReviewsResponse\x12(\n" +
	"\areviews\x18\x01 \x03(\v2\x0e.review.ReviewR\areviews2\x9c\x02\n" +
	"\rReviewService\x12>\n" +
	"\tAddReview\x12\x18.review.AddReviewRequest\x1a\x17.review.GenericResponse\x12C\n" +
	"\n" +
	"GetReviews\x12\x19.review.GetReviewsRequest\x1a\x1a.review.GetReviewsResponse\x12@\n" +
	"\n" +
	"EditReview\x12\x19.review.EditReviewRequest\x1a\x17.review.GenericResponse\x12D\n" +
	"\fDeleteReview\x12\x1b.review.DeleteReviewRequest\x1a\x17.review.GenericResponseB\x1fZ\x1dreview-service/proto;reviewpbb\x06proto3"

var (
	file_proto_review_proto_rawDescOnce sync.Once
	file_proto_review_proto_rawDescData []byte
)

func file_proto_review_proto_rawDescGZIP() []byte {
	file_proto_review_proto_rawDescOnce.Do(func() {
		file_proto_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_review_proto_rawDesc), len(file_proto_review_proto_rawDesc)))
	})
	return file_proto_review_proto_rawDescData
}

var file_proto_review_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_review_proto_goTypes = []any{
	(*AddReviewRequest)(nil),    // 0: review.AddReviewRequest
	(*GetReviewsRequest)(nil),   // 1: review.GetReviewsRequest
	(*EditReviewRequest)(nil),   // 2: review.EditReviewRequest
	(*DeleteReviewRequest)(nil), // 3: review.DeleteReviewRequest
	(*GenericResponse)(nil),     // 4: review.GenericResponse
	(*Review)(nil),              // 5: review.Review
	(*GetReviewsResponse)(nil),  // 6: review.GetReviewsResponse
}
var file_proto_review_proto_depIdxs = []int32{
	5, // 0: review.GetReviewsResponse.reviews:type_name -> review.Review
	0, // 1: review.ReviewService.AddReview:input_type -> review.AddReviewRequest
	1, // 2: review.ReviewService.GetReviews:input_type -> review.GetReviewsRequest
	2, // 3: review.ReviewService.EditReview:input_type -> review.EditReviewRequest
	3, // 4: review.ReviewService.DeleteReview:input_type -> review.DeleteReviewRequest
	4, // 5: review.ReviewService.AddReview:output_type -> review.GenericResponse
	6, // 6: review.ReviewService.GetReviews:output_type -> review.GetReviewsResponse
	4, // 7: review.ReviewService.EditReview:output_type -> review.GenericResponse
	4, // 8: review.ReviewService.DeleteReview:output_type -> review.GenericResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_review_proto_init() }
func file_proto_review_proto_init() {
	if File_proto_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_review_proto_rawDesc), len(file_proto_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_review_proto_goTypes,
		DependencyIndexes: file_proto_review_proto_depIdxs,
		MessageInfos:      file_proto_review_proto_msgTypes,
	}.Build()
	File_proto_review_proto = out.File
	file_proto_review_proto_goTypes = nil
	file_proto_review_proto_depIdxs = nil
}
